### ISSUE TITLE
can't convert lirc config to json

### ISSUE THREAD

**Issue by leifliddy** [zmoteio/zmote-dbmodels#1]
I'm trying to convert this dyson lirc remote config to a json record:
https://github.com/rys/dyson-cool-ir-lirc/blob/master/lircd.conf

I've converted it to an xml file using lirc2xml
http://www.bengt-martensson.de/harc/lirc2xml.html#Installation

Now, when I try converting it to a json record with 
./xml2js.pl dyson.xml | node > dyson.json
I receive the following error. 
-----------------------------------------------------------
/bin/sh: encodeirz: command not found
child_process.js:524
    throw err;
    ^
Error: Command failed: encodeirz none 0 0 0 0
/bin/sh: encodeirz: command not found

    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
......
-----------------------------------------------------------
I know next to nothing about java script. Could you help me convert this?
Ultimately, I'm just trying to convert the buttons on this remote to individual sendir commands, ie:
'sendir,1:1,0,38000,2,1,171,170,19,19BBB19,57CBBCCCCBBBB19,171CBBBBBBBCCC19,21CCCCBBBC19,2248'
 
If I just run:
./xml2js.pl dyson.xml 
I do get output for each button, I'm just not sure how to use it, ie:
remote.key('BTN_0', 'none', 0, 0, 0, 'none', '0000 006d 0011 0000 0054 001e 001d 003c 001d 001f 001d 001f 001d 003c 001d 001f 001d 001f 001d 001f 001d 001f 001d 001f 001d 001f 001d 001f 001d 001f 001d 001f 001d 001f 001d 001f 001d 08f5');

**I'm using Fedora 25 with nodejs-6.10.2-1

**Comment by urmilparikh** [comment]
You can build `encodeirz` from `zmote` branch of https://github.com/klarsys/encodeir
